### ISSUE TITLE
npm start gives error

### ISSUE THREAD

**Issue by rkanani108** [syncfusion/ej2-typescript-seed#5]
Hi @ajithr/ @SyncfusionInstall  ,

Gives below error when 'npm start' with below version.
npm: 6.14.8
node: v12.19.0

> ej2-typescript-seed@0.0.1 start C:\Users\rkanani\Documents\A\B\ej2-typescript-seed
> gulp start

fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (C:\Users\rkanani\Documents\A\B\ej2-typescript-seed\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\rkanani\Documents\A\B\ej2-typescript-seed\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\rkanani\Documents\A\B\ej2-typescript-seed\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ej2-typescript-seed@0.0.1 start: `gulp start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ej2-typescript-seed@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rkanani\AppData\Roaming\npm-cache\_logs\2020-10-22T09_45_37_714Z-debug.log

**Comment by jesusarockias** [comment]
Sorry for the inconvenience.

We want to inform you that the repository is using Gulp 3 which is not supported in latest version of Node.js setup. We request you to follow the below steps to fix this issue. 

1.	Clone/download and extract the repository
2.	Run the “npm install” command
3.	Then, change the package.json as below
`  "scripts": {
    "start": "gulp start",
    "serve": "gulp e2e-serve",
    "test": "gulp e2e-test",
    "build": "webpack --mode production",
    "update-webdriver": "gulp e2e-webdriver-update",
    "preinstall": "npx npm-force-resolutions"
  },
  "resolutions": {
    "graceful-fs": "^4.2.4"
  }


`
4.	Again, run “npm install” command
5.	Now, running “npm run start” will work.

Reference Image:
 
![image](https://user-images.githubusercontent.com/41784897/96864895-c6e4f900-1486-11eb-8fae-e16c61d5fe9c.png)


Please get back to us if you need any further assistance on this.

**Comment by pitMobile** [comment]
Hello,

I have the same issue. Unfortunately the fix of @jesusarockias does not work.

> C:\Projekte\Web\Spikes\syncfusion\quickstart>npm run start
> 
> >ej2-quickstart@0.0.1 start
> >gulp start
> 
> fs.js:45
> } = primordials;
>     ^
> 
> ReferenceError: primordials is not defined
>     at fs.js:45:5
>     at req_ (C:\Projekte\Web\Spikes\syncfusion\quickstart\node_modules\natives\index.js:143:24)
>     at Object.req [as require] (C:\Projekte\Web\Spikes\syncfusion\quickstart\node_modules\natives\index.js:55:10)
>     at Object.<anonymous> (C:\Projekte\Web\Spikes\syncfusion\quickstart\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
>     at Module._compile (node:internal/modules/cjs/loader:1083:30)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
>     at Module.load (node:internal/modules/cjs/loader:948:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:789:14)
>     at Module.require (node:internal/modules/cjs/loader:972:19)
>     at require (node:internal/modules/cjs/helpers:88:18)
> npm ERR! code 1
> npm ERR! path C:\Projekte\Web\Spikes\syncfusion\quickstart
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "gulp start"

node -v ==> v15.0.1
npm -v ==> 7.0.3

**Comment by rkanani108** [comment]
Hi @jesusarockias,

Your solution is working for me.

Thanks' for the quick response.

**Comment by jesusarockias** [comment]
Hi @pitMobile, 

We suggest you to use latest LTS version of nodejs as well as to follow the step carefully.

Please get back to us if you have any queries. 

Also, we request you to check our online demo and documentation for quick start about Syncfusion component. 

https://ej2.syncfusion.com/home/
